name: deploy to mixhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ssh key generate
        run: |
          echo "$SSH_PRIVATE_KEY" > key
          chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MIXHOST_SECRET_KEY }} # GitHubに登録したmixhostへの秘密鍵を指定

      - name: create env file
        run: |
          echo "VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID" > .env
          echo "VITE_GOOGLE_API_KEY=$VITE_GOOGLE_API_KEY" >> .env
          echo "VITE_SCOPES=$VITE_SCOPES" >> .env
          echo "VITE_GA_TRACKING_ID=$VITE_GA_TRACKING_ID" >> .env
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
          VITE_SCOPES: ${{ secrets.VITE_SCOPES }}
          VITE_GA_TRACKING_ID: ${{ secrets.VITE_GA_TRACKING_ID }}

      - name: vite build
        run: |
          npm install
          npm run build

      - name: copy htaccess file
        run: |
          cp .htaccess.example dist/.htaccess

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avz --delete
          path: dist/ # mixhostに送りたいファイルのあるパスを指定
          remote_path: /home/bvzvxvoh/public_html/subdomains/sub9/ # mixhostのどこに同期させるか
          remote_host: fast5-blog.com
          remote_user: bvzvxvoh
          remote_port: 22
          remote_key: ${{ secrets.MIXHOST_SECRET_KEY }}
